# Creates a Win32 package and imports into a target Intune tenant
# Uses secrets on the repo - TENANT_ID, CLIENT_ID, and CLIENT_SECRET
# to import the package into a target tenant
name: New Win32 Update

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: Update name.
        required: true
        type: string
        default: AdobeAcrobatReaderDCMUI
      alternatepath:
        description: Alternate location of packages in github.
        required: false
        type: string
  workflow_call:
    inputs:
      package:
        description: Update name.
        required: true
        type: string
      alternatepath:
        description: Alternate location of packages in github.
        required: false
        type: string


jobs:
  create-package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Alternate path
        if: inputs.alternatepath != null
        #run: echo "Using package json files from other location"
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.alternatepath }}
          path: alternatepackages
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          #ref: main

      - name: Copy alternate packages
        if: inputs.alternatepath != null
        #id: test-package
        shell: powershell
        working-directory: ${{ github.workspace }}
        run: |
          Rename-Item -Path "${{ github.workspace }}\packages\" -NewName "packages.bak"
          Copy-Item -Path "${{ github.workspace }}\alternatepackages\packages\" -Destination "${{ github.workspace }}\" -Recurse 
          Test-Path "${{ github.workspace }}\packages\"

      - name: Test for package/s
        id: test-package
        shell: powershell
        working-directory: ${{ github.workspace }}
        run: |
          [System.Array] $Applications = ("${{ inputs.package }}").ToString() -split ","
          foreach ($App in $Applications) {
              $AppItem = $App.Trim()
              Test-Path -Path "${{ github.workspace }}\packages\Updates\$AppItem"
          }

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: "MSAL.PS::, IntuneWin32App::, Evergreen::, VcRedist::"
          updatable: true
          shell: powershell

      - name: List Modules
        id: list-modules
        shell: powershell
        run: |
          foreach ($module in @("MSAL.PS", "IntuneWin32App", "Evergreen", "VcRedist")) {
              $Version = (Get-Module -Name $module -ListAvailable | Select-Object -First 1).Version.ToString()
              Write-Host "$module version: $Version"
          }

      # Create the app package
      - name: Authn to the Graph API and create package/s
        id: upload-package
        shell: powershell
        working-directory: ${{ github.workspace }}
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          Import-Module -Name "MSAL.PS", "IntuneWin32App", "Evergreen", "VcRedist" -Force
          $params = @{
              Application  = "${{ inputs.package }}"
              Path         = "${{ github.workspace }}"
              Type         = "Updates"
          }
          .\scripts\New-PipelineWin32App.ps1 @params
